### ISSUE TITLE
Workflow 1: Query DHIS2 active `trackedEntityInstances` to create OpenMRS `patients`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/openfn-lime#1]
## Background, context, and business value
When MSF plans to create a new OpenMRS instance at a new location where they are provided services, they wish to: 

1. Export existing active `trackedEntityInstance` records from their global DHIS2 instance
2. Import as `patient` records in OpenMRS (which should assign a `uuid` to each record created)
3. And then update the original DHIS2 `trackedEntityInstance` records with the OpenMRS patient `uuid`

## The specific request, in as few words as possible
Please create 3 flow jobs to automate this process: 

1. wf1-1-getTEIs.js
2. wf1-2-createPatients.js
3. wf1-3-updateTEIs.js

### Diagram & Mapping Specs
- [See the Workflow 1 Diagram](https://lucid.app/lucidchart/8a73c59c-f62d-4e24-80de-d643b257f609/edit?view_items=emj2.JuTB0UE&invitationId=inv_ae2b3599-fb12-4a6a-917e-926c5e9325e0) for the detailed workflow automation requirements. 
- [See Mapping: Workflow 1](https://docs.google.com/spreadsheets/d/1jQyDKigzNUecK8cmxb0QonHvT_HZ6y950ReNRMVNQLo/edit#gid=426647407) for the detailed mapping specifications. 

### API Docs
- DHIS2: https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-240/tracker-deprecated.html
**Note that MSF is using DHIS2 older core version `2.33.5`, so I think we will use the older tracker API and I don't _think_ we need to update our adaptor.** But lmk what you find/if any issues!

- OpenMRS: https://rest.openmrs.org/#openmrs-rest-api

## state.json
DHIS2: 
- data: {}
- configuration: see LP `MSF DHIS2 Test Org (api user)`
- cursor: {} 

OpenMRS: 
- configuration: see LP `MSF OpenMRS Demo`

## expression.js
3 new jobs - please add to the `jobs` directory. 

## output.json
For step 2 - [here](https://github.com/OpenFn/openfn-lime/blob/main/sampleData/openmrs_createPatient.json) is a sample payload for creating patients in OpenMRS. 
For step 3 - [here](https://github.com/OpenFn/openfn-lime/blob/main/sampleData/dhis2_trackedEntityInstance.json) is a sample payload for a trackedEntityInstance in DHIS2.  

## Toggl
`MSF LIME Prototype 2023`

**Comment by aleksa-krolls** [comment]
@mtuchi this is ready to be worked on next once the `openmrs` adaptor is ready. FYI, please add the repo `openfn-lime` to your Zenhub view.

**Comment by aleksa-krolls** [comment]
@mtuchi example job 1 template
```
get('trackedEntityInstances', {
  ou: 'l22DQq4iV3G',
  program: 'uGHvY5HFoLG',
  //inactive: false //option 1 to filter by inactive
  filter: ['inactive:Eq:false'], //option 2 - TBD which option works
}, state => {
  console.log('TEI data ::', JSON.stringify(state.data)); 
  return state; 
});
```

**Comment by mtuchi** [comment]
@aleksa-krolls i made good progress so far on this, See my PR #2, 
I was facing this error 👇🏽 
```
Person must have at least one non-deleted name
```
I solved that one by adding 👇🏽 on `person` objectf
```
 names: [
    {
        givenName: 'Doe',
        familyName: 'John',
    },
],
```

Now i am facing this error 👇🏽 , i am not sure how to fix this
```
Invalid check digit for identifier: 006
```

**Comment by aleksa-krolls** [comment]
@mtuchi 
1. On partient name, your suggestion works well. Please map as specified in rows 12-13 of [the mapping spec](https://docs.google.com/spreadsheets/d/1jQyDKigzNUecK8cmxb0QonHvT_HZ6y950ReNRMVNQLo/edit#gid=426647407). 

2. To solve for the identifier issue, can you please try setting `"identifierType": "8d79403a-c2cc-11de-8d13-0010c6dffd0f"` to see if that allows you to set `"identifier": 006`. 
(I've updated the [sample payload](https://github.com/OpenFn/openfn-lime/blob/main/sampleData/openmrs_createPatient.json#L5) accordingly.)

**Comment by aleksa-krolls** [comment]
Ah wait @mtuchi I figured out how to set the patient `identifier`...
1. First you will to send a `POST` request to this endpoint with an empty request body `{}`
`http://msf-ocg-openmrs3-dev.westeurope.cloudapp.azure.com/openmrs/ws/rest/v1/idgen/identifiersource/8549f706-7e85-4c1d-9424-217d50a2988b/identifier`
This is to auto-generate an OpenMRS ID. 
2. This will return an `openmrsID` like `"identifier": "100007G"`. 
3. Then when you create the `patient`, you will map 2 identifiers as follows: 
```
"identifiers": [
        {
            "identifier": ${openmrsID}, //map the ID returned in step 2 above
            "identifierType":"05a29f94-c0ed-11e2-94be-8c13b969e334", //openmrs-generated ID 
            "location":"44c3efb0-2583-4c80-a79e-1f756a03c0a1",  //default location
            "preferred":true //default value for this identifiertype
        },
        {
            "identifier": ${dhis2.patient_number}, //map ID value from DHIS2 attribute
            "identifierType":"8d79403a-c2cc-11de-8d13-0010c6dffd0f", //Old Identification number
            "location":"44c3efb0-2583-4c80-a79e-1f756a03c0a1", //default location
            "preferred":false //default value for this identifiertype
        }
    ],
```

I have updated the [sample OpenMRS payload](https://github.com/OpenFn/openfn-lime/blob/main/sampleData/openmrs_createPatient.json) and will update the mapping spec accordingly, but lmk if you have any questions!

**Comment by aleksa-krolls** [comment]
@mtuchi for job 3 when we map openmrs `patient.uuid` back to the DHIS2 `trackedEntityInstance`
(fyi the DHIS2 attribute ID for "OpenMRS Patient ID" is `jGNhqEeXy2L`)
<img width="1411" alt="Screen Shot 2023-05-30 at 3 18 03 PM" src="https://github.com/OpenFn/openfn-lime/assets/16758106/542b87c1-2e68-4071-be73-68738afb4d20">
So we want to set `jGNhqEeXy2L: {patient.uuid}`

**Comment by aleksa-krolls** [comment]
@mtuchi example expression for upserting a TEI in DHIS2 
```
upsert('trackedEntityInstances', {
 ou: 'l22DQq4iV3G',
 filter: ['P4wdYGkldeG:Eq:${openmrs.patient_number}], // 'destinationFieldId:Eq:006`
}, {
 orgUnit: 'l22DQq4iV3G',
 program: 'uGHvY5HFoLG',
 trackedEntityType: 'cHlzCA2MuEF',
 attributes: [
   {
     attribute: 'P4wdYGkldeG',
     value: ${openmrs.patient_number },
   },
 {
     attribute: 'jGNhqEeXy2L',
     value: ${openmrs.uuid },
   },
 ],
});
```

**Comment by mtuchi** [comment]
@aleksa-krolls you can now test the workflow, The adaptor version is `@openfn/language-openmrs@1.0.0`. 
All recent changes are on the PR #2
