### ISSUE TITLE
`wf2` - add date cursor to job 1 when we get Patients

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/openfn-lime#11]
## Background, context, and business value
See issue #3 for more background. 

Currently we have a date cursor in `wf2-3` job when we get encounters. In testing, I'm finding that it will also be important to add this cursor to filter patients in the first job `wf2-1`.

## The specific request, in as few words as possible
1.  Please add a date cursor to `wf2-1` to filter patients where patient's `auditInfo.dateCreated` >  `lastRunTime || "2023-05-18T20:16:37.000+0000"`. 
(we can probably re-use code from `wf2-3`: https://github.com/OpenFn/openfn-lime/blob/main/jobs/wf2-3-getEncounters.js#L2-L13
2. If we implement this, do we need to make changes to the encounters cursor in `wf2-3`? Or can we keep this as is? 

## state.json
**DHIS2:**
-data: {}
-configuration: see LP `MSF DHIS2 Test Org (api user)
-cursor: TO ADD

**OpenMRS:**
-configuration: see LP `MSF OpenMRS Demo`

## expression.js
`wf2-1`: https://github.com/OpenFn/openfn-lime/blob/main/jobs/wf2-1-getPatients.js

## Toggl 

MSF LIME Prototype 2023

**Comment by aleksa-krolls** [comment]
@mtuchi one last cursor to add to workflow 2, job1!

**Comment by aleksa-krolls** [comment]
fyi @mtuchi I just tested and openmrs is in `GMT` time zone... so no adjustments needed for openmrs-related date cursors. (That request is only for DHIS2)

**Comment by mtuchi** [comment]
@aleksa-krolls this is ready for QA and test, See PR 👉🏽  #13
