### ISSUE TITLE
wf2-2: DHIS2 upsert does not allow us to enroll a trackedEntityInstance multiple times

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/openfn-lime#16]
## Background, context, and business value
Currently in WF 2 (see issue #3 for context), we "enroll" TEIs in a program during our upsert operation. Our mapping looks like this: 
https://github.com/OpenFn/openfn-lime/blob/686391889b0d5dabf16bb8089befacdbbf772735/jobs/wf2-2-upsertTEIs.js#L63-L70

Unfortunately if we run this job multiple times, DHIS2 allows us to successfully upsert this patient... but later when web users try to edit the record or add events, DHIS2 throws an error like `"Tracked entity instance: elPYH6OnN7Z has multiple active enrollments in program: uGHvY5HFoLG"`

It therefore seems that `enrollment` is being duplicated every time we run the upsert TEI job. 

## The specific request, in as few words as possible
We need to get replace the "upsert" operation in job `wf2-2` with logic that has different actions depending on whether the patient exists. Instead we need to...

1.  get TEIs from DHIS2 to check if patient exists

2. If TEI exists, then we should **update** the TEI with only the TEI attributes (`age`, `sex`) and NOT include `enrollments` in the payload
> See example payload: https://github.com/OpenFn/openfn-lime/blob/main/sampleData/dhis2_trackedEntityInstance.json

3. If TEI does _not_ exist, then we should **create** the TEI _AND_ include `enrollments: [*]` in the payload 
> See example payload: https://github.com/OpenFn/openfn-lime/blob/main/sampleData/dhis2_TEIwithEnrollment.json

See updated WF diagram: 
https://lucid.app/lucidchart/8a73c59c-f62d-4e24-80de-d643b257f609/edit?viewport_loc=216%2C1006%2C3117%2C1354%2CSd-0A22pdvy4&invitationId=inv_ae2b3599-fb12-4a6a-917e-926c5e9325e0
<img width="490" alt="Screen Shot 2023-06-07 at 3 54 34 PM" src="https://github.com/OpenFn/openfn-lime/assets/16758106/18d52323-bff8-4596-b1a6-0f2ff09194ac">

## state.json
Re-run job `wf2-1` to generate state for `wf2-2`

**DHIS2:**
- data: {}
- configuration: see LP `MSF DHIS2 Test Org (api user)`
- cursor: use `manualCursor`

**OpenMRS:**
- configuration: see LP `MSF OpenMRS Demo`

## expression.js
Branch off main 
https://github.com/OpenFn/openfn-lime/blob/main/jobs/wf2-2-upsertTEIs.js

## Toggl 
MSF LIME

**Comment by aleksa-krolls** [comment]
@mtuchi We have 1 change request for the MSF workflow 2. Ping me whenever you start work on this one, and we can jump into a meet to discuss.

**Comment by aleksa-krolls** [comment]
@mtuchi the PR is merged, so please branch off `main` now for this. 
As discussed: 
1. Get TEI to see if record already exists
2. If exists, build TEI payload _without_ enrollment
3. If new, build TEI payload _WITH_ enrollment
4. Then upsert each TEI 

For 2 and 3 - see here for an example output that has 1 new patient and 1 existing patient: https://github.com/OpenFn/openfn-lime/blob/main/sampleData/dhis2_newANDexistingTEIs.json

**Comment by mtuchi** [comment]
@aleksa-krolls this is not fixed at #19, feel free to merge and test

**Comment by aleksa-krolls** [comment]
Thank you! @daissatou2 can you please merge and re-test the WF2 scenarios? Let us know how it goes on Slack
