### ISSUE TITLE
Update wf2-3 job to use the same cursor as wf2-1 job

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/openfn-lime#17]
## Describe the bug and expected behavior 
The cursor in workflow 2 job 3 is currently not linked to the cursor in job 1. This means that when I clear job state or update the cursor for job 1, the workflow properly fetches new/updated OMRS patients since the last sync (in job 1), however, it is not properly fetching the enrollments created since the last sync (in job 3).

Update the workflow to pass the cursor for job 1 to job 3. Job 3 should not be using it's own different cursor, it should be using the same cursor as job 1. 

## To Reproduce
In this run [log](https://www.openfn.org/projects/msf-lime/runs/06480792-b681-7035-9586-90ab223a5598), job 3 is using the cursor `2023-06-07T12:33:33.948Z` (which is the time that the job ran). It should instead be using the same cursor from job 1 ` 2023-06-01T07:50:00.000+0000` --see job 1's [run log](https://www.openfn.org/projects/msf-lime/runs/06480791-b224-7b00-9b16-0ca8d84eb6e9). 

### expression.js
Link to the job itself in Github:https://github.com/OpenFn/openfn-lime/blob/main/jobs/wf2-3-getEncounters.js  
Adaptor: `openmrs`

### state.json
Re-run job wf2-1 to generate state for wf2-3

**DHIS2:**
- data: {}
- configuration: see LP `MSF DHIS2 Test Org (api user)`
- cursor: use `manualCursor`

**OpenMRS:**
- configuration: see LP `MSF OpenMRS Demo`

## To test/resolve
1. After the desired output is working locally (from the CLI), please [open a pull request].
2. [Please test the change on OpenFn.org by re-running this run ([link](https://www.openfn.org/projects/msf-lime/runs/064807ab-d768-747f-98d7-6c32eaf335c4)) and confirming success.]

## Toggl 
`MSF LIME`

**Comment by mtuchi** [comment]
@daissatou2 if the cursor is on job 1 does it mean the `lastRunDateTime` is suppose to be set on the last job ? job 5 
or which job should set the `lastRunDateTime` ?

**Comment by daissatou2** [comment]
If the cursor is set on job 1 shouldn't the `lastRunDateTime` also be set by job 1? Otherwise, we might miss some data that was created or updated in between when job 1 was triggered and job 5 finished running.

**Comment by mtuchi** [comment]
@daissatou2  This will be fixed in the latest improvements PR https://github.com/OpenFn/openfn-lime/pull/18
