### ISSUE TITLE
`WF2-5. Create Events in DHIS2` job is failing on platform 

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/openfn-lime#22]
## Describe the bug and expected behavior 
The `WF2-5. Create Events in DHIS2` job is failing on platform with the following error message: 
`TypeError [Error]: Cannot read properties of undefined (reading 'trackedEntityInstance')`

## To Reproduce
1. Here is a link to a failed run on OpenFn.org which is indicative of the bug: https://www.openfn.org/projects/msf-lime/runs/0648aa9a-6610-7335-9e01-b48fdef76ba9

The cursor for WF2-1 job on platform to replicate this error: `2023-06-14T06:01:24.544Z` 

### expression.js
Link to the job itself in Github: https://github.com/OpenFn/openfn-lime/blob/main/jobs/wf2-5-createEvents.js  
Adaptor: DHIS2

### state.json

Either provide state directly, or link to a file. If sensitive information
should be in state, redact it and provide instructions for where it can be
found.

```json
{
  "configuration": ["SEE LAST PASS: 'MSF OpenMRS Demo'"],
  "data": "data generated by Job WF2-3",
  "cursor": "2023-06-14T06:01:24.544Z"
}
```

## To test/resolve
1. After the desired output is working locally (from the CLI), please [open a pull request].
3. [Please test the change on OpenFn.org by re-running this run (https://www.openfn.org/projects/msf-lime/runs/0648aa9a-6610-7335-9e01-b48fdef76ba9) and confirming success.]

## Toggl 
`MSF LIME Prototype 2023`

**Comment by mtuchi** [comment]
@daissatou2 this seems to be fixed now, see recent run log here - https://www.openfn.org/projects/msf-lime/runs/0648b139-ac5b-7e66-8293-54b1763e8a5d

I have revert the `manualCursor` to `2023-06-14T06:01:24.544Z`. Let me know if you need more help with this

**Comment by daissatou2** [comment]
Mtuchi successfully tested locally with a cursor date of May 20th (because job 2 was timing out on platform because of the number of records). I rested with a new patient (create, update, and create encounter) and my tests also passed.
