### ISSUE TITLE
Workflow 2: Sync OpenMRS `patients` & `encounters` back to DHIS2 Tracker

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/openfn-lime#3]
## Background, context, and business value
Following Workflow 1 (see issue #1 ), MSF will start to collect data in its new OpenMRS instance. For reporting and program monitoring, it would like to regularly send patient and encounter data collected back to the global DHIS2 system. This workflow will: 

1. Get `patient` records from the local OpenMRS instance
2. Upsert the patients as `trackedEntityInstances` in DHIS2
3. Get patients' `encounter` records from OpenMRS
4. Upsert the encounters as `events` in DHIS2, and use Open Concept Lab ("OCL") mappings to re-assign the OpenMRS values to DHIS2-compatible values for 2 fields (`Entry triage color` & `Final diagnosis`)

## The specific request, in as few words as possible
Please create 5 jobs to automate this process: 

**1. wf2-1-getPatients.js**
> GET '/patient?q=Patient &v=full'`
> This should return a response like [this payload](https://github.com/OpenFn/openfn-lime/blob/main/sampleData/openmrs_getPatientsFull.json).

**2. wf2-2-upsertTEIs.js**
> In your request body, include `ou=l22DQq4iV3G&filter:jGNhqEeXy2L:Eq:${patient.uuid}` to upsert on patient uuid
> [See here](https://github.com/OpenFn/openfn-lime/blob/main/sampleData/dhis2_trackedEntityInstance.json) for an example TrackedEntityInstance JSON payload. 

**3. wf2-3-getEncounters.js**
> GET '/encounter?q=Patient &v=full'`
> This should return a response like [this payload](https://github.com/OpenFn/openfn-lime/blob/main/sampleData/openmrs_getEncountersFull.json).

After we get an array of encounters, we should **filter** this to only return encounters where `encounterDatetime >= cursorDate` WHERE `cursorDate = lastRunDateTime || 2023-05-23T00:00:00.000`

**4. wf2-4-getOclMap.js**
> This should return JSON [like this](https://api.openconceptlab.org/orgs/MSFOCG/collections/lime-demo/HEAD/expansions/autoexpand-HEAD/mappings/?q=&page=1&exact_match=off&limit=200&verbose=false&fromConceptOwner=MSFOCG&toConceptOwner=MSFOCG&toConceptSource=DHIS2DataElements&sortDesc=_score). 
> For each object in the array, to map the OpenMRS data to DHIS2, we are interested in the values for the OCL keys `from_concept_name_resolved` and `to_concept_name_resolved `. 

**5. wf2-5-createEvents.js**
> I don't _think_ we can create `events` in Bulk for DHIS2 (please confirm - bc if not, we will have to send a POST request for each event to sync.
> [See here](https://github.com/OpenFn/openfn-lime/blob/main/sampleData/dhis2_event.json) for an example DHIS2 event payload. 

### Diagram & Mapping Specs
- [See the Workflow 2 Diagram](https://lucid.app/lucidchart/8a73c59c-f62d-4e24-80de-d643b257f609/edit?view_items=Sd-0ZlH0yCmk&invitationId=inv_ae2b3599-fb12-4a6a-917e-926c5e9325e0). 
- See Mapping specs for the 2 DHIS2 upsert operations: 
1. [Upsert TEI (step 1)](https://docs.google.com/spreadsheets/d/1jQyDKigzNUecK8cmxb0QonHvT_HZ6y950ReNRMVNQLo/edit#gid=1822444315)
2. [Create event (step 2)](https://docs.google.com/spreadsheets/d/1jQyDKigzNUecK8cmxb0QonHvT_HZ6y950ReNRMVNQLo/edit#gid=2025635257)

### API Docs
- DHIS2: https://docs.dhis2.org/en/develop/using-the-api/dhis-core-version-240/tracker-deprecated.html
**Note that MSF is using DHIS2 older core version `2.33.5`, so I think we will use the older tracker API and I don't _think_ we need to update our adaptor.** But lmk what you find/if any issues!

- OpenMRS: https://rest.openmrs.org/#openmrs-rest-api

- OCL: see [swagger API docs](https://api.openconceptlab.org/swagger/)
And [see this link](https://app.openconceptlab.org/#/orgs/MSFOCG/collections/lime-demo/mappings/?q=&isTable=true&isList=false&page=2&exactMatch=off&limit=100&facets={%22fromConceptOwner%22:{%22MSFOCG%22:true},%22toConceptOwner%22:{%22MSFOCG%22:true},%22toConceptSource%22:{%22DHIS2DataElements%22:true}}) or the user-friendly front-end view of the mappings conigured

## state.json
**DHIS2**: 
- data: {}
- configuration: see LP `MSF DHIS2 Test Org (api user)`
- cursor: {} 

**OpenMRS**: 
- configuration: see LP `MSF OpenMRS Demo`

**OCL** (public project, so you shouldn't need auth... just the URL)
- configuration: {"baseURL": "https://api.openconceptlab.org/orgs/MSFOCG/collections/lime-demo/HEAD/expansions/autoexpand-HEAD/mappings/?q=&page=1&exact_match=off&limit=200&verbose=false&fromConceptOwner=MSFOCG&toConceptOwner=MSFOCG&toConceptSource=DHIS2DataElements&sortDesc=_score"}

## expression.js
5 new jobs - please add to the `jobs` directory. 

## output.json
To upsert a DHIS2 `trackedEntityInstance`, see sample payload: https://github.com/OpenFn/openfn-lime/blob/main/sampleData/dhis2_trackedEntityInstance.json

example expression: 
```
upsert('trackedEntityInstances', {
 ou: 'l22DQq4iV3G',
 filter: ['jGNhqEeXy2L:Eq:${patient.uuid}], 
}, {
 orgUnit: 'l22DQq4iV3G',
 program: 'uGHvY5HFoLG',
 trackedEntityType: 'cHlzCA2MuEF',
 attributes: [
   {
     attribute: 'attributeId',
     value: ${openmrs.value },
   }
 ],
});
```

To create a DHIS2 `event` related to the previously created `trackedEntityInstance`, see payload: https://github.com/OpenFn/openfn-lime/blob/main/sampleData/dhis2_event.json

## Toggl
`MSF LIME Prototype 2023`

**Comment by aleksa-krolls** [comment]
@mtuchi to work on tomorrow in our pairing session 💪... in the morning, please have a read through before we jump on.

**Comment by aleksa-krolls** [comment]
@mtuchi WF2 job 1 fails immediately on platform. Can you please check it out ASAP? (so that I can test the rest of the workflow)
https://www.openfn.org/projects/msf-lime/runs/0647831b-946f-75fb-86a9-accacfdc8acb

When I send a GET request to `/patient?q=Patient'` on Postman, it works great - not sure what's up. 

Also this seems like a strange error message (and not something we get from the OpenMRS API). What does this mean? `Error: Raising an error because undefined records were found.`

**Comment by mtuchi** [comment]
> @mtuchi WF2 job 1 fails immediately on platform. Can you please check it out ASAP? (so that I can test the rest of the workflow) https://www.openfn.org/projects/msf-lime/runs/0647831b-946f-75fb-86a9-accacfdc8acb
> 
> When I send a GET request to `/patient?q=Patient'` on Postman, it works great - not sure what's up.
> 
> Also this seems like a strange error message (and not something we get from the OpenMRS API). What does this mean? `Error: Raising an error because undefined records were found.`

@aleksa-krolls i have fixed it, it was the adaptor version issue, Please make sure all jobs use `v1.0.1`

Sorry i forgotten to mention that

**Comment by aleksa-krolls** [comment]
@mtuchi so far tests are passing! But I need to do further inspection to 100% confirm. To help...

Is it possible to log the `trackedEntityInstance` ID in the job `wf2-5` where we create `events`. See example [run log](https://www.openfn.org/projects/msf-lime/runs/064783bb-27ef-713a-b3d7-17638a7ebf81) where I can see the event ID... but it would also be really helpful to see the related TEI's ID that we GET in the first step of this job.

**Comment by mtuchi** [comment]
> @mtuchi so far tests are passing! But I need to do further inspection to 100% confirm. To help...
> 
> Is it possible to log the `trackedEntityInstance` ID in the job `wf2-5` where we create `events`. See example [run log](https://www.openfn.org/projects/msf-lime/runs/064783bb-27ef-713a-b3d7-17638a7ebf81) where I can see the event ID... but it would also be really helpful to see the related TEI's ID that we GET in the first step of this job.

@aleksa-krolls i have added the `console.log()` after creating an event, See 👉🏽  a055d83 for changes i made 
You can try to test now

**Comment by aleksa-krolls** [comment]
Nice!
