### ISSUE TITLE
Update job `wf2-4` to use `ocl` adaptor

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/openfn-lime#7]
## Request
It looks like we're using `http`, rather than the `ocl` adaptor. Is there a reason for that? 

## expression.js
Create a new branch off `main`... do NOT merge to main. (I want to test on a different branch so we don't impact the client demo today.)
https://github.com/OpenFn/openfn-lime/blob/main/jobs/wf2-4-getOclMap.js

## state.json
No auth needed. 

Re-run jobs `wf2-1`, `wf2-2`, and ``wf2-3` to generate state for this job. See issue #3 for the configuration details. 

## Toggl 

`MSF LIME Prototype 2023`

**Comment by mtuchi** [comment]
@aleksa-krolls , we don't have a `fetch()` or `get()` helper function in `langauge-ocl`, that's why we are using `language-http`

In our `ocl` adaptor we only `auth()` and `map()` - https://docs.openfn.org/adaptors/packages/ocl-docs#map

**Comment by mtuchi** [comment]
@aleksa-krolls this issue depends on this PR - https://github.com/OpenFn/adaptors/pull/270
I will update the job shortly after this is resolved and merged to main

Also something. to be aware of there has improvements, https://github.com/OpenFn/openfn-lime/pull/15
i am still working on Joe's feedback. I will let you know once this is done as well

**Comment by aleksa-krolls** [comment]
@mtuchi is this actively being worked on? (Or simply waiting on the new adaptor version to be released?)

**Comment by mtuchi** [comment]
@aleksa-krolls Already worked on #15 , it's waiting for the new adaptor release

**Comment by aleksa-krolls** [comment]
@mtuchi  see below for the http job that works as expected. To test the OCL adaptor, can you create a job that uses the same parameters as below? 
(If the OCL job's response includes `"DOA"` and `"Acute abdomen"` then we know the ocl-version of the job is working the same as this http-version.)
```
get('https://api.openconceptlab.org/orgs/MSFOCG/collections/lime-demo/HEAD/expansions/autoexpand-HEAD/mappings', {
   query: { 
     page: 1, 
     limit: 1000,
     verbose: false, 
     fromConceptOwner: 'MSFOCG', 
     toConceptOwner: 'MSFOCG',
     toConceptSource: 'DHIS2DataElements',
     sortDesc: '_score'
   },
   headers: {'content-type': 'application/json'},
 }); 
```
Once you've (1) confirmed the ocl-adaptor version of the job is working, _and_ (2) the new ocl adaptor is released, please submit a PR to update Job `wf2-4` in the workflow and confirm which ocl adaptor version we should use.

**Comment by aleksa-krolls** [comment]
@mtuchi is this ready for testing... looks like PR is in draft mode? (Do not merge - I will merge when I am ready to test later.)
When it's ready to go, please leave me a comment here with the ocl adaptor version I should use, as requested. Thanks!

**Comment by mtuchi** [comment]
> @mtuchi is this ready for testing... looks like PR is in draft mode? (Do not merge - I will merge when I am ready to test later.) When it's ready to go, please leave me a comment here with the ocl adaptor version I should use, as requested. Thanks!

@aleksa-krolls i have just made a release for the `ocl` adaptor and `openmrs` adaptor. Please merge this PR #21 and test using these versions 👇🏽 
```
@openfn/language-ocl@0.3.0
@openfn/language-openmrs@1.1.1
```

**Comment by aleksa-krolls** [comment]
@mtuchi I finally merged the ocl PR and it broke the workflow. See [this run failure](https://www.openfn.org/projects/msf-lime/runs/0649887b-51c5-7219-a796-524a524f1f1a) with error: 
`Error: Cannot find module './priv/language_packs/node_modules/@openfn/language-ocl-v0.3.0'.`
cc @taylordowns2000 

Please let me know how to fix this ASAP so that the client can keep using it, and ping me on Slack if you have any questions.

**Comment by mtuchi** [comment]
@aleksa-krolls i have fixed the problem, the adaptor had new breaking changes i forgotten to mention that last Friday
[See the run log ](https://www.openfn.org/projects/msf-lime/runs/064992c0-cf7e-7cd9-ac17-d2e7420a7c45)
