### ISSUE TITLE
`wf1-1` add cursor to only get recently created `trackedEntityInstances`

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/openfn-lime#8]
## Background, context, and business value
For background see issue #1 . 
Right now I am unable to re-run Workflow 1 multiple times, because we "create" (and not upsert) in OpenMRS. I would like to be able to re-test this workflow so that every time I create a new TEI in DHIS2, I would like to sync it back to OpenMRS. 

## The specific request, in as few words as possible
Please add a cursor to filter the response after we `GET '/trackedEntityInstances'`: 
- Each TEI in the GET response will have a date like this `"created": "2023-06-01T09:00:00.000"`
- Can you please add a date cursor filtering that only returns TEIs `created > lastRunTime || '2023-06-01T09:00:00.000'`

## state.json
DHIS2 adaptor
- data: {}
- configuration: see LP `MSF DHIS2 Test Org (api user)`
- cursor: TOADD for `created` date

## expression.js
Please create a new branch off of `main`
https://github.com/OpenFn/openfn-lime/blob/main/jobs/wf1-1-getTEIs.js

## Toggl 

MSF LIME Prototype 2023

**Comment by aleksa-krolls** [comment]
@mtuchi can you help me with this to optimize testing? 
To test it out...
1. If you set the default manual cursor to `2023-06-01T09:00:00.000` (as requested), I think this will return 0 results
2. If you set it instead to `2023-06-01T08:00:00.000` (1 hour earlier), this should return 1 or more TEI records

**Comment by mtuchi** [comment]
@aleksa-krolls let me give it a try 

> @mtuchi can you help me with this to optimize testing? To test it out...
> 
> 1. If you set the default manual cursor to `2023-06-01T09:00:00.000` (as requested), I think this will return 0 results
> 2. If you set it instead to `2023-06-01T08:00:00.000` (1 hour earlier), this should return 1 or more TEI records

**Comment by mtuchi** [comment]
@aleksa-krolls i have updated `wf1-1-getTEIs.js` to use a cursor, I am using this `2023-06-01T08:00:00.000` as the manual cursor. At the time of testing this cursor  `2023-06-01T09:00:00.000` return `0 TEIs` while this cursor`2023-06-01T08:00:00.000` returns `4 TEIs`

**Comment by aleksa-krolls** [comment]
@mtuchi it works well, but unfortunately this cursor uses `GMT` and the DHIS2 system uses Geneva time `GMT+2`. 

When we generate a new `lastRunDateTime`, would it be possible to add 2 hours so that it matches the DHIS2 time localization? 

See run log that shows 7a instead of 9a: https://www.openfn.org/projects/msf-lime/runs/0647844f-857a-7f9d-99bb-b6b3b89dbef0

**Comment by mtuchi** [comment]
@aleksa-krolls i have pushed and merge the fix, Please try again
